AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for AWS Glue base setup'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)
    AllowedValues: 
      - dev
      - staging
      - prod
    
  GlueDatabaseName:
    Type: String
    Default: alfred_brain_data
    Description: Name for the AWS Glue Database
    
  S3BucketName:
    Type: String
    Description: S3 bucket name for ETL job scripts and temporary data storage
    
  GlueIAMRoleName:
    Type: String
    Default: AlfredBrainGlueRole
    Description: IAM role name for AWS Glue

Resources:
  # IAM Role for Glue
  GlueIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${GlueIAMRoleName}-${EnvironmentName}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: !Sub ${GlueIAMRoleName}-S3Access-${EnvironmentName}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub arn:aws:s3:::${S3BucketName}
                  - !Sub arn:aws:s3:::${S3BucketName}/*
        - PolicyName: !Sub ${GlueIAMRoleName}-CloudWatchLogs-${EnvironmentName}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: AlfredBrain

  # AWS Glue Database
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref GlueDatabaseName
        Description: AWS Glue database for Alfred Brain data

Outputs:
  GlueDatabaseName:
    Description: Name of the AWS Glue Database
    Value: !Ref GlueDatabaseName
    Export:
      Name: !Sub ${AWS::StackName}-GlueDatabaseName
      
  GlueRoleName:
    Description: Name of the IAM role for Glue
    Value: !Ref GlueIAMRole
    Export:
      Name: !Sub ${AWS::StackName}-GlueRoleName
      
  GlueRoleArn:
    Description: ARN of the IAM role for Glue
    Value: !GetAtt GlueIAMRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-GlueRoleArn