AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Alfred Brain S3 bucket configuration'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)
    AllowedValues: 
      - dev
      - staging
      - prod
    
  BucketName:
    Type: String
    Default: alfred-brain-data
    Description: Base name for the S3 bucket (will be prefixed with environment)
    
  AccessLogBucketEnabled:
    Type: String
    Default: 'false'
    Description: Enable S3 bucket access logging
    AllowedValues: 
      - 'true'
      - 'false'

  ExpirationDays:
    Type: Number
    Default: 90
    Description: Number of days after which objects are deleted (0 to disable)
    MinValue: 0

  TransitionToColdStorageDays:
    Type: Number
    Default: 30
    Description: Number of days after which objects are transitioned to cold storage (0 to disable)
    MinValue: 0
    
Conditions:
  IsProd: !Equals [!Ref EnvironmentName, 'prod']
  IsStaging: !Equals [!Ref EnvironmentName, 'staging']
  IsDev: !Equals [!Ref EnvironmentName, 'dev']
  EnableAccessLog: !Equals [!Ref AccessLogBucketEnabled, 'true']
  EnableExpiration: !Not [!Equals [!Ref ExpirationDays, 0]]
  EnableTransition: !Not [!Equals [!Ref TransitionToColdStorageDays, 0]]

Resources:
  # Main S3 Bucket
  AlfredBrainDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${EnvironmentName}-${BucketName}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration: !If
        - EnableAccessLog
        - DestinationBucketName: !Ref AlfredBrainLogsBucket
          LogFilePrefix: !Sub ${EnvironmentName}-${BucketName}-logs/
        - !Ref AWS::NoValue
      LifecycleConfiguration:
        Rules:
          - Id: DataLifecycleRule
            Status: Enabled
            ExpirationInDays: !If
              - EnableExpiration
              - !Ref ExpirationDays
              - !Ref AWS::NoValue
            Transitions: !If
              - EnableTransition
              - - StorageClass: STANDARD_IA
                  TransitionInDays: !Ref TransitionToColdStorageDays
              - !Ref AWS::NoValue
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: AlfredBrain

  # Access Logs Bucket (Created only if access logging is enabled)
  AlfredBrainLogsBucket:
    Type: AWS::S3::Bucket
    Condition: EnableAccessLog
    Properties:
      BucketName: !Sub ${EnvironmentName}-${BucketName}-logs
      AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: LogsLifecycleRule
            Status: Enabled
            ExpirationInDays: 90
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: AlfredBrain

  # Bucket Policy for main data bucket
  AlfredBrainDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AlfredBrainDataBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceSSLOnly
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub arn:aws:s3:::${EnvironmentName}-${BucketName}
              - !Sub arn:aws:s3:::${EnvironmentName}-${BucketName}/*
            Condition:
              Bool:
                aws:SecureTransport: false

Outputs:
  DataBucketName:
    Description: Name of the Alfred Brain data bucket
    Value: !Ref AlfredBrainDataBucket
    Export:
      Name: !Sub ${AWS::StackName}-DataBucketName
      
  DataBucketArn:
    Description: ARN of the Alfred Brain data bucket
    Value: !GetAtt AlfredBrainDataBucket.Arn
    Export:
      Name: !Sub ${AWS::StackName}-DataBucketArn
      
  LogsBucketName:
    Description: Name of the Alfred Brain logs bucket
    Condition: EnableAccessLog
    Value: !Ref AlfredBrainLogsBucket
    Export:
      Name: !Sub ${AWS::StackName}-LogsBucketName